export enum NotificationType {
  SERVICE_REQUEST = 'service_request',
  SERVICE_ACCEPTED = 'service_accepted',
  SERVICE_REJECTED = 'service_rejected',
  SERVICE_COMPLETED = 'service_completed',
  // Tarea 5 (I-05, platform-hardening-2026-09, 2026-09-14) — valores nuevos guiados por la
  // columna "Evento" de la tabla de I-05-notification-triggers.md, uno por cada disparo
  // IMPRESCINDIBLE que no tenía tipo todavía.
  SERVICE_CANCELLED = 'service_cancelled',
  BUDGET_OPTIONS_READY = 'budget_options_ready',
  BUDGET_OPTION_SELECTED = 'budget_option_selected',
  CONTRACT_CREATED = 'contract_created',
  CONTRACT_AWAITING_SIGNATURE = 'contract_awaiting_signature',
  CONTRACT_SIGNED = 'contract_signed',
  PAYMENT_REFUNDED = 'payment_refunded',
  DOCUMENT_APPROVED = 'document_approved',
  DOCUMENT_REJECTED = 'document_rejected',
  DISPUTE_OPENED = 'dispute_opened',
  DISPUTE_RESOLVED = 'dispute_resolved',
  ACCOUNT_DELETION_REQUESTED = 'account_deletion_requested',
  ACCOUNT_DELETION_CANCELLED = 'account_deletion_cancelled',
  PROFESSIONAL_VERIFIED = 'professional_verified',
  PROFESSIONAL_VERIFICATION_REJECTED = 'professional_verification_rejected',
  PROFESSIONAL_SUSPENDED = 'professional_suspended',
  PAYMENT_RECEIVED = 'payment_received',
  RATING_RECEIVED = 'rating_received',
  PROMOTION = 'promotion',
  SYSTEM = 'system',
  DOCUMENT_EXPIRED = 'document_expired',
}
