apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tekoapp-backend
  namespace: default
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deploy-tekoapp-backend
  template:
    metadata:
      name: deploy-tekoapp-backend
      labels:
        app: deploy-tekoapp-backend
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/auth-path: auth/dev-k3s
        vault.hashicorp.com/role: tekoapp-backend-role
        vault.hashicorp.com/agent-run-as-user: '1001'
        vault.hashicorp.com/agent-inject-secret-tekoapp-backend-configmap: project/data/dev/tekoapp-backend-configmap
        vault.hashicorp.com/agent-inject-template-tekoapp-backend-configmap: |
          {{- with secret "project/data/dev/tekoapp-backend-configmap" -}}
          {{- range $key, $value := .Data.data }}
            export {{ $key }}="{{ $value }}"
          {{- end }}
          {{ end }}
    spec:
      serviceAccountName: tekoapp-backend
      imagePullSecrets:
        - name: regcred
      enableServiceLinks: false
      containers:
        - image: ghcr.io/josepanz/tekoapp-backend:1.0.0-develop.1
          resources:
            limits:
              cpu: '800m'
              memory: '400Mi'
            requests:
              cpu: 100m
              memory: 100Mi
          name: deploy-tekoapp-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          command:
            - '/bin/sh'
            - '-c'
            - |
              . /vault/secrets/tekoapp-backend-configmap
              node dist/main
          startupProbe:
            httpGet:
              path: /tekoapp-backend/api/healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /tekoapp-backend/api/healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /tekoapp-backend/api/healthcheck
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
