export enum EmailTypeEnum {
  VERIFICATION = 'VERIFICATION',
  FORGOT_PASSWORD = 'FORGOT-PASSWORD',
  CREATE_PASSWORD = 'CREATE-PASSWORD',
  PAYMENT_RECEIPT = 'PAYMENT-RECEIPT',
  // Tarea 6 (platform-hardening-2026-09, 2026-09-14) — avisos de seguridad pedidos por José.
  LOGIN = 'LOGIN',
  PASSWORD_CHANGED = 'PASSWORD-CHANGED',
  PASSWORD_RESET = 'PASSWORD-RESET',
  PAYMENT_METHOD_CREATED = 'PAYMENT-METHOD-CREATED',
}
